export enum ViewProviderCommand {
    deleteRokuFile = 'deleteRokuFile',
    getAppUI = 'getAppUI',
    getStoredAppUI = 'getStoredAppUI',
    getScreenshot = 'getScreenshot',
    getStoredRokuAppOverlays = 'getStoredRokuAppOverlays',
    getVscodeContext = 'getVscodeContext',
    getWorkspaceState = 'getWorkspaceState',
    loadRokuAppOverlaysThumbnails = 'loadRokuAppOverlaysThumbnails',
    openRokuFile = 'openRokuFile',
    runRokuAutomationConfig = 'runRokuAutomationConfig',
    sendMessageToWebviews = 'sendMessageToWebviews',
    sendReplRequest = 'sendReplRequest',
    setManualIpAddress = 'setManualIpAddress',
    setVscodeContext = 'setVscodeContext',
    stopRokuAutomationConfig = 'stopRokuAutomationConfig',
    storeRokuAppOverlays = 'storeRokuAppOverlays',
    storeRokuAutomationConfigs = 'storeRokuAutomationConfigs',
    updateWorkspaceState = 'updateWorkspaceState',
    viewReady = 'viewReady'
}
