export enum ViewProviderEvent {
    onNodeFocused = 'onNodeFocused',
    onDeviceAvailabilityChange = 'onDeviceAvailabilityChange',
    onVscodeCommandReceived = 'onVscodeCommandReceived',
    onRegistryUpdated = 'onRegistryUpdated',
    onStoredAppUIUpdated = 'onStoredAppUIUpdated',
    onRokuAutomationConfigsLoaded = 'onRokuAutomationConfigsLoaded',
    onRokuAutomationImportAllAutomations = 'onRokuAutomationImportAllAutomations',
    onRokuAutomationExportAllAutomations = 'onRokuAutomationExportAllAutomations',
    onRokuAutomationConfigStepChange = 'onRokuAutomationConfigStepChange',
    onRokuAutomationKeyPressed = 'onRokuAutomationKeyPressed',
    onRokuAppOverlayAdded = 'onRokuAppOverlayAdded',
    onRokuAppOverlayThumbnailsLoaded = 'onRokuAppOverlayThumbnailsLoaded',
    onVscodeContextSet = 'onVscodeContextSet',
    onRceStateChanged = 'onRceStateChanged',
    onRceStreamConnecting = 'onRceStreamConnecting',
    onRceStreamOffer = 'onRceStreamOffer',
    onRceStreamError = 'onRceStreamError',
    onRceStreamClosed = 'onRceStreamClosed'
}
