export enum VscodeCommand {
    rokuDeviceViewRefreshScreenshot = 'extension.brightscript.rokuDeviceView.refreshScreenshot',
    rokuDeviceViewResumeScreenshotCapture = 'extension.brightscript.rokuDeviceView.resumeScreenshotCapture',
    rokuDeviceViewPauseScreenshotCapture = 'extension.brightscript.rokuDeviceView.pauseScreenshotCapture',
    rokuDeviceViewCopyScreenshot = 'extension.brightscript.rokuDeviceView.copyScreenshot',
    rokuDeviceViewEnableNodeInspector = 'extension.brightscript.rokuDeviceView.enableNodeInspector',
    rokuDeviceViewDisableNodeInspector = 'extension.brightscript.rokuDeviceView.disableNodeInspector',
    rokuRegistryExportRegistry = 'extension.brightscript.rokuRegistry.exportRegistry',
    rokuRegistryImportRegistry = 'extension.brightscript.rokuRegistry.importRegistry',
    rokuRegistryClearRegistry = 'extension.brightscript.rokuRegistry.clearRegistry',
    rokuRegistryRefreshRegistry = 'extension.brightscript.rokuRegistry.refreshRegistry',
    rokuAutomationViewEnableAutorunOnDeploy = 'extension.brightscript.rokuAutomationView.enableAutorunOnDeploy',
    rokuAutomationViewDisableAutorunOnDeploy = 'extension.brightscript.rokuAutomationView.disableAutorunOnDeploy',
    rokuAutomationViewStartRecording = 'extension.brightscript.rokuAutomationView.startRecording',
    rokuAutomationViewStopRecording = 'extension.brightscript.rokuAutomationView.stopRecording',
    rokuAutomationViewImportAutomation = 'extension.brightscript.rokuAutomationView.importAutomation',
    rokuAutomationViewExportAutomation = 'extension.brightscript.rokuAutomationView.exportAutomation',
    enableRemoteControlMode = 'extension.brightscript.enableRemoteControlMode',
    disableRemoteControlMode = 'extension.brightscript.disableRemoteControlMode',
    rokuAppOverlaysViewAddNewOverlay = 'extension.brightscript.rokuAppOverlaysView.addNewOverlay',
    rokuAppOverlaysViewRemoveAllOverlays = 'extension.brightscript.rokuAppOverlaysView.removeAllOverlays',
    rokuFileSystemViewRefresh = 'extension.brightscript.rokuFileSystemView.refresh',
    disconnectFromDevice = 'extension.brightscript.disconnectFromDevice',
    openSceneGraphInspectorInPanel = 'extension.brightscript.openSceneGraphInspectorInPanel',
    clearNpmPackageCache = 'extension.brightscript.clearNpmPackageCache'
}
