name: publish-docs
on:
  push:
    branches:
      - 'master'
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14.19.0"
      - run: npm install
      - run: npm run build-docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .tmp/docs
          CLEAN: true # Automatically remove deleted files from the deploy branch